### PR TITLE
Fix general bugs (fix #155, fix #156, fix #147, fix #154, fix #149)

### LINKED ISSUE #147: Add log out to menu
Logging in is a bit finicky as @vojtaholik has experienced. I would like to add a log out menu item which also logs you out of the staging endpoint so that you can get a clean login for testing.

### LINKED ISSUE #149: The revenue graph makes the initial page scroll horizontally
As seen on the screenshot the revenue graph causes the page to scroll. If I recall correctly this is something that got changed not too long ago.

image uploaded from ios 1

### LINKED ISSUE #154: Resolve HoneyBadger runtime errors

### LINKED ISSUE #155: Remove "d" on approve action

### LINKED ISSUE #156: Fix getLoginUrl for auth

### PR DESCRIPTION
**Pull request by trevordmiller**
# Changes

- Fix client-side authentication
- Improve SSR through mocks instead of conditionals for `window`
- Add logout button to navigation when logged in
- Address HoneyBadger runtime errors
- Fix revenue container width matching
- Version bump for patch release

# Result For User

fix-revenue

---

### CODE REVIEW

File: src/package/utils/lessonStates/index.js [hunk 1]
```diff
@@ -51,16 +51,16 @@ export const detailsByLessonState = {
     icon: 'refresh',
   },
   approved: {
-    action: 'Approved',
+    action: 'Approve',
```
Comment (trevordmiller) [inline src/package/utils/lessonStates/index.js:54]: Remove typo "d"

File: src/package/utils/lessonStates/index.js [hunk 2]
```diff
@@ -17,25 +17,25 @@ export const detailsByLessonState = {
     action: 'Accept',
     description: 'This lesson has been accepted - it can be claimed.',
     color: 'green',
-    icon: 'check',
+    icon: 'add',
```
Comment (trevordmiller) [inline src/package/utils/lessonStates/index.js:20]: Replace check icons on lesson actions with "+" for now to avoid confusion with the new instructor get published checklist check icons
https://github.com/eggheadio/egghead-ui/issues/142

File: src/package/utils/windowMock/index.js [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+    reload: () => null,
+  },
+  localStorage: {
+    setItem: () => null,
+    getItem: () => null,
+    removeItem: () => null,
+  },
+}
+
+export default windowMock
```
Comment (trevordmiller) [inline src/package/utils/windowMock/index.js:13]: Was going to use a library for this, but they were all really heavy or had global side effects; this is simpler.

**Review by tayiorbeii — APPROVED** [review]

**Review by theianjones — APPROVED** [review]
